### ISSUE TITLE
PowerBar disables experimental features

### ISSUE THREAD

**Issue by SupLiCatinG** [jeroentvb/spicetify-power-bar#10]
When i activate powerbar on my config, it disables experimental features.

**Comment by jeroentvb** [comment]
What spotify and spicetify version are you using?

**Comment by SupLiCatinG** [comment]
> What spotify and spicetify version are you using? And is there showing any error in the console?

Reloading spotify resolving issue but i dont know how to solve this.

**Comment by jeroentvb** [comment]
If I understand you correctly, everything is working again?

**Comment by SupLiCatinG** [comment]
Yeap
