### ISSUE TITLE
Add a Setting to Customize Power-Bar Colours. 

### ISSUE THREAD

**Issue by niv-dev** [jeroentvb/spicetify-power-bar#28]
Right now, I think it just borrows from the current custom theme, this looks really ugly for a few themes and it would be a life saver to change it either from in-built settings or in a config file. 

For reference, this is what power-bar looks like for me:

![image](https://user-images.githubusercontent.com/79858886/175805331-117216bd-22e9-45b5-9b4e-feae388880b3.png)

**Comment by jeroentvb** [comment]
Creating a settings section to change the colors would take a lot of time and in my opinion, the power bar shouldn't handle styling other than trying to fit in with spotify's default theme as best as possible.

I do agree that your screenshot doesn't look all too good, so I've changed the css a bit to make it easy to overwrite the css variables used by the power bar to set custom colors.

So with that change, theme creators can add their own styling to style the power bar in the colors of the theme. Alternatively you can change the styling yourself using the 'add css' button in the spicetify marketplace's snippet section, or use an extension like [css-editor](https://github.com/FlafyDev/spotify-css-editor). Info on what css to add can be found [here](https://github.com/jeroentvb/spicetify-power-bar/blob/dev/README.md#theme).

If you agree with these changes, I'll merge them to master and publish a new release.

**Comment by niv-dev** [comment]
Perfect, works like a charm, lets merge them to master!
