### ISSUE TITLE
Add suggestion to queue instead of playing it when holding ctrl (windows/linux) or cm (mac) is not working on mac

### ISSUE THREAD

**Issue by Climax-Arc** [jeroentvb/spicetify-power-bar#32]
cant add songs to queue using cmd key

idk i was doing it wrong but all i was doing is holding cmd and hit enter

 - OS: mac os 12.6
 - Spicetify version: 1.1.94.870.gf994cb0b
 - Spotify version: 2.13.1

**Comment by jeroentvb** [comment]
Do you have the toggle in the settings enabled that says 'Add suggestion to queue instead of playing it when holding...'?

**Comment by Climax-Arc** [comment]
I did enabled it

**Comment by jeroentvb** [comment]
Looks like the endpoint I used to push the selected item to the queue changed. The endpoint returns a 400 error now. Will have a look at it later today.

**Comment by Climax-Arc** [comment]
Thanks for responding and working on it :)

**Comment by jeroentvb** [comment]
> Looks like the endpoint I used to push the selected item to the queue changed. The endpoint returns a 400 error now. Will have a look at it later today.

Seems like I was wrong. The endpoint hasn't changed. I did dig a little bit and found that adding to the queue fails when nothing has been played recently.
For example when launching spotify and adding a song to the queue with the power bar without having played anything first. I know it also breaks sometimes when adding a song to the queue after having listened for a while, but I can't really reproduce that.

I think the best course of action is handling the error that is being thrown, so you at least get some feedback.

If you have some other realiable reproduction steps I could take, I'd very much like to hear them 😄

**Comment by Climax-Arc** [comment]
i tried it while playing, at launching spotify, after a while still same thing nothing happening
is there any config files i can send that'll help you?

**Comment by jeroentvb** [comment]
The only things that will help are reliable reproduction steps, or an error log. You could try opening the console and see if any errors are being thrown.

**Comment by Climax-Arc** [comment]
ForbiddenError: POST request to https://api.spotify.com/v1/me/player/queue?uri=spotify:track:29d0nY7TzCoi22XBqDQkiP failed with status code 403
    at e.value (xpui.js:1:2019235)
    at onSuccess (xpui.js:1:2019011)
![Screenshot](https://user-images.githubusercontent.com/62397588/193450250-ee879da9-ae54-4cff-bf51-fabee1036b3d.jpg)

**Comment by Climax-Arc** [comment]
is that what you asking?

**Comment by jeroentvb** [comment]
Yes. Sadly, that's the same error I'm only getting when I haven't played anything yet and try to add something to the queue. Unfortunately there's not really anything I can do about that right now.

**Comment by Climax-Arc** [comment]
i was getting while playing song idk why, anyways thanks taking time for answering :)

**Comment by jeroentvb** [comment]
Are you still having this issue? Or can I (or you) close it?
