### ISSUE TITLE
[feat] Add translations ?

### ISSUE THREAD

**Issue by xerta555** [jeroentvb/spicetify-power-bar#34]
Hi

It could be possible to add a translations system to this great extension ?

There is not much things to translate, but it would be nice to implement it, but i can understand if it's too hard to implement.

Thanks in advance.

**Comment by xerta555** [comment]
Thx for this enhancement, now how to translate it ?

**Comment by jeroentvb** [comment]
@xerta555 most of the power bar ui is now using the translations from 'Spicetify.Platform.Translations', which means it's using the language you set Spotify to. So no need to translate anything manually.

**Comment by xerta555** [comment]
> @xerta555 most of the power bar ui is now using the translations from 'Spicetify.Platform.Translations', which means it's using the language you set Spotify to. So no need to translate anything manually.

Ok i ask that bcz i see that the settings related to this module aren't translated, the categories are effectivly translated, but not the settings.
How the settings strings could be translated ?

**Comment by jeroentvb** [comment]
I haven't implemented a way to do that. The parts that are currently translated leverage Spotify's existing translations
