### ISSUE TITLE
It doesn't work at all, I tried everything and it just doesn't work, I haven't experienced it, I'm using it on a mac

### ISSUE THREAD

**Issue by youthyan** [jeroentvb/spicetify-power-bar#39]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**
<img width="901" alt="截屏2023-05-01 下午3 15 29" src="https://user-images.githubusercontent.com/105373147/235421534-9008c7c4-d987-4deb-b17f-f4c368393e51.png">

**Device info (please complete the following information):**

<img width="214" alt="截屏2023-05-01 下午3 16 13" src="https://user-images.githubusercontent.com/105373147/235421619-082bc220-5a73-41d1-bf80-71e20b26aef7.png">

**Additional context**

**Comment by jeroentvb** [comment]
I need more info. Just tested on my mac and it works fine. Your spicetify version is out-of-date though, so try updating and see if it works.

If not, I need to know what you tried. Reproduction steps are also _really_ helpful.

**Comment by jeroentvb** [comment]
I'm closing this issue as I can't really do anything with the provided information. Feel free to re-open if/when you can supply more ifno regarding the issue.
