### ISSUE TITLE
Settings don't appear where they should

### ISSUE THREAD

**Issue by Hi-ImKyle** [jeroentvb/spicetify-power-bar#46]
**Describe the bug**
The readme says that Power Bar settings are within the Spotify Settings page but upon looking and searching, there are no settings related to Power Bar within that page.

**To Reproduce**
1. Install Power Bar
2. Try to access Power Bar settings

**Expected behavior**
For the Power Bar settings to show

**Screenshots**
n/a

**Device info (please complete the following information):**
 - OS: Windows 10
 - Spicetify version: 2.22.2
 - Spotify version: 1.2.17.834.g26ee1129

**Additional context**
n/a

**Comment by Hi-ImKyle** [comment]
I'm going to guess that Power Bar at the moment is out of date considering I can't even use it with the default settings. Ctrl Space to open it up on Windows does nothing.

**Comment by jeroentvb** [comment]
Are you using power-bar via the marketplace. If so, could you try again and see if it's working again?

I published a fix for something that broke power-bar ~1 hour before you created this issue. I believe the method the marketplace uses to fetch extension files from github takes time to update. So this issue may have been resolved already but you may not have gotten the updated file at that time.

**Comment by Hi-ImKyle** [comment]
Yeah, all good. Saw your response, figured I'd leave it a bit for things to propagate. Got the updated one now, all is good 👍
