### ISSUE TITLE
No results displaying when searching

### ISSUE THREAD

**Issue by Tobias-Brugger** [jeroentvb/spicetify-power-bar#50]
**Describe the bug**
When I search something with the power bar no results are displaying.

**To Reproduce**
Press ctrl + space; typing in what you want to search = no results

![image](https://github.com/jeroentvb/spicetify-power-bar/assets/89259696/ddee4368-34d4-4368-b6f0-98525a824321)

**Expected behavior**
Of course, the search result

 - OS: Win11
 - Spotify 1.2.31.1205.g4d59ad7c
-  Spicetify v2.29.1

**Comment by jeroentvb** [comment]
This is due to Spotify changing something internally resulting in the api calls not being authenticated.

I can fix this manually, but am currently waiting for Spicetify to fix this.

https://github.com/spicetify/spicetify-cli/issues/2844

**Comment by jeroentvb** [comment]
Tested and confirmed!
