### ISSUE TITLE
Cannot change activation key combo

### ISSUE THREAD

**Issue by Mysticc28** [jeroentvb/spicetify-power-bar#52]
Hello, when I first installed this extension, it worked great. However, now it has stopped working and I cannot even change the activation key combo. It just shows as blank and does not register any keys being pressed when I try to change it. Issue screenshot is attached below. 
![image](https://github.com/user-attachments/assets/86b9e9de-242a-43ef-901f-56b8eca33dba)

**Comment by Mysticc28** [comment]
Update: has been fixed after reinstall. If you;re facing a problem with this, type out the text of the keys and paste it in like ctrl,ControlRight or altkey and find what works

**Comment by jeroentvb** [comment]
This does seem to work fine for me. You do however need to clear the field first before trying to register a new key combo.
