### ISSUE TITLE
Add support for non-english characters  

### ISSUE THREAD

**Issue by SupLiCatinG** [jeroentvb/spicetify-power-bar#9]
It's annoying i even cannot search with artist's original name.

https://user-images.githubusercontent.com/94017480/151990782-8cc757b7-66e7-4f9d-a9bb-6171dcb7ef39.mov

**Comment by jeroentvb** [comment]
Can you provide a few strings (artist names) that do give search results in spotify's search page but not in the power bar?

**Comment by SupLiCatinG** [comment]
> Can you provide a few strings (artist names) that do give search results in spotify's search page but not in the power bar?


Kıvırcık Ali Özütemiz > can find by typing "Kivircik Ali Ozutemiz"
Onur Akın > can find by typing "Onur Akin"
Barış Akarsu > can find by typing "Baris Akarsu"

**Comment by jeroentvb** [comment]
Thanks. It looks like it currently fails due to non-encoded search query in the url, which shouldn't be hard to fix.
